name: afya_dz
description: The Ultimate Healthcare App.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- 1. أساسيات فايربيز (Firebase Core) ---
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19

  # --- 2. الأدوات والاتصال (Utilities & Network) ---
  url_launcher: ^6.2.5
  intl: ^0.19.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  flutter_local_notifications: ^17.1.2

  # --- 3. التصميم والخرائط (UI & Maps) ---
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  animate_do: ^3.3.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- 4. أيقونة التطبيق ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# --- إعدادات الأيقونة ---
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # تم إرجاع اسم الصورة كما طلبت
  image_path: "Picsart_26-01-15_11-27-34-308.png"
  min_sdk_android: 21
