name: Afya
description: Healthcare app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  url_launcher: ^6.2.5
  geolocator: ^11.0.0
  intl: ^0.19.0
  image_picker: ^1.0.7  # <--- الإضافة الجديدة (أداة الصور)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Picsart_26-01-13_15-36-20-384.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
